apiVersion: v1
kind: Service
metadata:
  name: gedis-0
spec:
  ports:
    - port: 5431
      name: gedis
  clusterIP: None
  selector:
    app: gedis
    statefulset.kubernetes.io/pod-name: gedis-0
---
apiVersion: v1
kind: Service
metadata:
  name: gedis
  labels:
    app: gedis
spec:
  ports:
    - port: 5431
      name: gedis
      targetPort: 5431
  selector:
    app: gedis
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gedis
spec:
  selector:
    matchLabels:
      app: gedis
  serviceName: "gedis"
  replicas: 3
  template:
    metadata:
      labels:
        app: gedis
    spec:
      containers:
        - name: gedis
          args: ["-port", "5431", "-leader", "gedis-0:5431", "-n", "3", "-id", "$(POD_NAME)", "-listen", "$(POD_IP):5431"]
#          - -leader gedis-0
#          - -n 3
#          - -id $POD_NAME
          image: ko://github.com/dalbar/gedis/cmd/server
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 5431
              name: gedis
